library("NetworkDistance")
library("corrplot")
library("VisuNet")
library("reshape2")
library("ggplot2")
library("ggpubr")
library("igraph")

source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/generate_object.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/generateNet.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/filtration_rules.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/filtration_rules_10per.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/data_input.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/RDF_columns_test.R')
source('/Users/mateuszgarbulowski/Desktop/VisuNet/R/Viewrules_type_L.R')